server:
  port: 8088
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  issuer: novastart
  secret: 3JRwE0S34MtAqToVPAz4W0EaB3lYer3io4j9FblK1xNPO7KIJEwRkhmYDzWUZMs0komra1uq/GwuX7oa6jC6gw==
  tokenExpireTime: 1440
  tokenHeaderKey: Authorization
  tokenPrefix: Bearer


#=================================================================
# minio
#=================================================================
minio:
  endpoint: https://img.xxx.com
  accessKey: xxx
  secretKey: xxx
  bucketName: xxx
