server:
  port: 8080
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  issuer: quanxiaoha
  secret: gR6cytlUlgMfVh08nLFZf8hMk4mdJDX5rWBVlsCbKvRlWcLwNRU6+rIPcLx21x191kJgP8udtoZuHt5yUDWtgg==
  tokenExpireTime: 1440
  tokenHeaderKey: Authorization
  tokenPrefix: Bearer


#=================================================================
# minio
#=================================================================
minio:
  endpoint: https://img.xxx.com
  accessKey: xxx
  secretKey: xxx
  bucketName: xxx
