server:
  port: 9001
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  issuer: quanxiaoha
  secret: gR6cytlUlgMfVh08nLFZf8hMk4mdJDX5rWBVlsCbKvRlWcLwNRU6+rIPcLx21x191kJgP8udtoZuHt5yUDWtgg==
  tokenExpireTime: 1440
  tokenHeaderKey: Authorization
  tokenPrefix: Bearer

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-not-delete-value: 0
      logic-delete-value: 1
